apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  # Add fields here
  clusterNetwork:
    pods:
      cidrBlocks: []
    services:
      cidrBlocks: ["10.96.0.0/12"]
    serviceDomain: cnct.io
